version: '3.6'

services:
   eip:
     image: pilotfishtechnology/eiplatform:latest
     container_name: eiplatform
     ports:
       - "8080:8080"
     restart: on-failure
     environment:
# Pilotfish License
       - PFISH_EIP_CONF_com_pilotfish_eip_license_base64=
# Memory allocation pool for a Java virtual machine
       - JAVA_OPTS=-Xms1g -Xmx3g -Dcom.pilotfish.eip.environmentSettings.file=environment-settings.conf
# Set Time Zone
#       - TIMEZONE=America/New_York
# Performance enhancement that skips execution of any stages that do not alter data
#       - PFISH_EIP_CONF_com_pilotfish_eip_skipEmptyStages=false
# Specifies if a thread pool should be created per-Route, or per-Stage. Per-Stage is the default setting
#       - PFISH_EIP_CONF_com_pilotfish_eip_ntm_poolPerRoute=true
# Thread pool configuration settings for per-Stage thread pools. Only applies if PoolPerRoute is false.
#       - PFISH_EIP_CONF_com_pilotfish_eip_ntm_maxThreadCount=8
#       - PFISH_EIP_CONF_com_pilotfish_eip_ntm_baseThreadCount=2
#       - PFISH_EIP_CONF_com_pilotfish_eip_ntm_maxThreadCount=8
#       - PFISH_EIP_CONF_com_pilotfish_eip_ntm_stage_idleTimeout=60
#       - PFISH_EIP_CONF_com_pilotfish_eip_ntm_stage_stageQueueSize=-1
#       - PFISH_EIP_CONF_com_pilotfish_eip_ntm_allowCoreTimeout=false
# Thread pool configuration settings for per-Route thread pools. Only applies if PoolPerRoute is true.
#       - PFISH_EIP_CONF_com_pilotfish_eip_transact_baseThreadCount=4
#       - PFISH_EIP_CONF_com_pilotfish_eip_transact_maxThreadCount=8
#       - PFISH_EIP_CONF_com_pilotfish_eip_transact_queueSize=-1
#       - PFISH_EIP_CONF_com_pilotfish_eip_transact_idleTimeout=60
# PilotFish Transaction Cache Type
#       - PFISH_EIP_CONF_com_pilotfish_eip_transact_defaultCache=memory
# Docker Health Check 
#   The /healthcheck.sh script triggers a curl to confirm if the container is up and running. 
#   If there is any failure, the container will be terminated and automatically be restarted by the ‘restart: on-failure’ tag within docker-compose.
#   This is enabled by default
#       - ENABLE_HEALTHCHECK=1

     volumes:
       - ./eip-root/:/opt/pilotfish/eip-root/
# Possible extra volume mappings for debugging purposes
#       - ./license/:/opt/pilotfish/license/
#       - ./config/:/opt/pilotfish/config/
#       - ./logs/:/opt/pilotfish/logs/