version: '3.6'

services:
   eip:
     image: pilotfishtechnology/eiplatform:latest
     container_name: eiplatform
     ports:
       - "8080:8080"
     restart: on-failure
     environment:
       - JAVA_OPTS=-Xms1g -Xmx3g
     volumes:
       - ./eip-root/:/opt/pilotfish/eip-root/
       - ./license/:/opt/pilotfish/license/
       - ./config/:/opt/pilotfish/config/
       - ./logs/:/opt/pilotfish/logs/